# Generated by Django 5.1.6 on 2025-02-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('country_region', models.CharField(max_length=100)),
                ('continent', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('total_cases', models.IntegerField()),
                ('total_death', models.IntegerField()),
                ('total_recovered', models.IntegerField()),
                ('active_cases', models.IntegerField()),
            ],
        ),
    ]
