# Generated by Django 5.0.12 on 2025-02-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coviddata',
            old_name='total_death',
            new_name='total_deaths',
        ),
        migrations.RemoveField(
            model_name='coviddata',
            name='date',
        ),
    ]
