# Generated by Django 5.0.12 on 2025-02-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_data', '0002_rename_total_death_coviddata_total_deaths_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='active_cases',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='population',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='total_cases',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='total_deaths',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='total_recovered',
            field=models.IntegerField(null=True),
        ),
    ]
