# Generated by Django 5.0.12 on 2025-02-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_data', '0003_alter_coviddata_active_cases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='population',
            field=models.BigIntegerField(null=True),
        ),
    ]
