# Generated by Django 5.0.12 on 2025-04-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("covid_data", "0004_alter_coviddata_population"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coviddata",
            name="active_cases",
        ),
        migrations.CreateModel(
            name="OWIDCovidData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iso_code", models.CharField(max_length=10)),
                ("continent", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("total_cases", models.FloatField(blank=True, null=True)),
                ("new_cases", models.FloatField(blank=True, null=True)),
                ("total_deaths", models.FloatField(blank=True, null=True)),
                ("new_deaths", models.FloatField(blank=True, null=True)),
                ("total_cases_per_million", models.FloatField(blank=True, null=True)),
                ("new_cases_per_million", models.FloatField(blank=True, null=True)),
                ("total_deaths_per_million", models.FloatField(blank=True, null=True)),
                ("new_deaths_per_million", models.FloatField(blank=True, null=True)),
                ("population_density", models.FloatField(blank=True, null=True)),
                ("median_age", models.FloatField(blank=True, null=True)),
                ("aged_65_older", models.FloatField(blank=True, null=True)),
                ("aged_70_older", models.FloatField(blank=True, null=True)),
                ("gdp_per_capita", models.FloatField(blank=True, null=True)),
                ("cardiovasc_death_rate", models.FloatField(blank=True, null=True)),
                ("diabetes_prevalence", models.FloatField(blank=True, null=True)),
                ("life_expectancy", models.FloatField(blank=True, null=True)),
                ("population", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["location"], name="covid_data__locatio_2054cd_idx"
                    ),
                    models.Index(fields=["date"], name="covid_data__date_76caed_idx"),
                    models.Index(
                        fields=["iso_code"], name="covid_data__iso_cod_1d8482_idx"
                    ),
                ],
                "unique_together": {("location", "date")},
            },
        ),
    ]
